server:
  port: 8080
  servlet:
    context-path: /youqian
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/youqian?serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 2
      default-auto-commit: true
      initial-size: 2
      min-idle: 0
      max-wait: 5000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 60000
      log-abandoned: true
      remove-abandoned: true
      remove-abandoned-timeout: 120
      filters: stat
mybatis:
  config-location: classpath:mybatis/mybatis-conf.xml
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
shiro:
  loginUrl: "/user/login"

